# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5af7b510cca032cd1630874e48c4465949cd8464c81bc596d1030134539d68200360d85be4d3510bff3de816f950f6e8b74542550fadf8522f14d69b6a0f294

test:
  secret_key_base: bb165e8f62e2cb0d547e752766a8b79bc163bd9bd34051fd6d1c61cc0083051072d11925fbf91a98ec20004c6e5c74b5abe1564db8d9074ef4cacff17ce330cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
